image: jangrewe/gitlab-ci-android

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"
  - export OC_RELEASE_KEYSTORE="$(pwd)/signing-key.jks"
  - echo "$SIGNING_KEY_JKS" | base64 -d > "$OC_RELEASE_KEYSTORE"
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
    - build/outputs/
